## Setup

Before running the examples in this file, make sure that **NumPy** is available.

NumPy is used for numerical computing and working with arrays, which are fundamental in machine learning.

### Installing NumPy

Open the terminal and run:

```bash
pip install numpy
```

If the command above does not work, try:

```bash
python -m pip install numpy
```

In [1]:
import numpy as np

## Creating NumPy Arrays

### array

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [3]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### arange

Return evenly spaced values within a given interval.

General syntax:

```python
np.arange(start, stop, step)
```

* start: Starting value (included).
* stop: Ending value (not included).
* step: Spacing between values. It is optional and defaults to 1.

In [4]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### linspace

Returns evenly spaced numbers over a specified interval.

General syntax:

```python
np.linspace(start, stop, num)
```

* start: The starting value. (included)
* stop: The ending value. (included)
* num: The number of values to generate.


In [6]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [7]:
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

### zeros and ones

Generate arrays filled with zeros or ones.

```python
np.zeros(shape)
np.ones(shape)
```

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(4)


array([1., 1., 1., 1.])

In [11]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### zeros_like and ones_like

np.zeros_like() and np.ones_like() create a new array filled with zeros or ones, respectively, with the same shape as an existing array.

\* Both functions use the shape and data type of the input array by default.

In [ ]:
v = np.array([[1, 2, 3],
              [4, 5, 6]])

zeros = np.zeros_like(v)
# np.zeros(v.shape())
ones = np.ones_like(v)

print(zeros)
print(ones)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


### full

Creates an array of a given shape and fills it with a specified value.

```python
np.full(shape, fill_value)
```


In [13]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])


### eye

Creates an identity matrix.

```python
np.eye(n)
```

\* *n* is the number of rows and columns in the identity matrix.

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### rand

Creates an array of the given shape and fills it with random samples from a uniform distribution over the interval [0, 1).

```python
np.random.rand(d1, d2, ...)
```

In [15]:
np.random.rand(5)

array([0.15355733, 0.19915234, 0.74020181, 0.93822961, 0.03544174])

In [16]:
np.random.rand(2, 2, 2)

array([[[0.83845358, 0.71145332],
        [0.49515594, 0.7794938 ]],

       [[0.16547211, 0.53416778],
        [0.69159366, 0.70139495]]])

### randn

Generates random samples from the standard normal distribution, which has a mean of 0 and a standard deviation of 1.

Unlike **rand**, which follows a uniform distribution, values closer to 0 are more likely to occur.

```python
np.random.randn(d0, d1, ...)
```

In [17]:
np.random.randn(5)

array([ 0.00680779, -0.86921955, -1.41513958,  0.10485316,  0.40522203])

In [18]:
np.random.randn(2, 3)

array([[ 0.89862708,  0.04208958,  0.06245084],
       [ 1.6994849 ,  0.15569964, -0.98727682]])

### normal

normal is similar to randn. The difference is that randn generates samples from a standard normal distribution, while normal lets you control the distribution's parameters, such as the mean and standard deviation.

General syntax:

```python
np.random.normal(loc, scale, size)
```

* loc: Mean of the distribution. Defaults to 0.
* scale: Standard deviation of the distribution. Defaults to 1.
* size: Shape of the output array. It is optional.

When loc=0 and scale=1, np.random.normal() is equivalent in distribution to np.random.randn().


In [19]:
np.random.normal(10, 2, 5)

array([ 8.96975434,  7.8612553 ,  9.88629856, 11.86508754,  6.12985915])

In [20]:
np.random.normal(5, 4, (2, 2))

array([[5.37093155, 6.0564977 ],
       [4.47875981, 6.72401833]])

### randint

Generates random integers from low (inclusive) to high (exclusive).

General syntax:

```python
np.random.randint(low, high, size)
```

* low: The lower bound (included).
* high: The upper bound (excluded).
* size: The shape of the output array.

In [21]:
np.random.randint(1, 10)

8

In [22]:
np.random.randint(1, 10, (2, 3))

array([[8, 5, 1],
       [7, 7, 7]], dtype=int32)

## Array Methods

Let's discuss some useful methods for an array:

### seed

Sets the random seed so that the same random results can be reproduced.

This is useful when you want your code to produce the same random values each time it is run.

In [71]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

### reshape

Changes the shape of an array without changing its data.

\* The total number of elements must remain the same. For example, an array with 6 elements can be reshaped into (2, 3), (3, 2), or (6,), but not (2, 4).


In [24]:
a = np.arange(6)
b = a.reshape(2, 3)
print("a\n", a)
print("b\n", b)

a
 [0 1 2 3 4 5]
b
 [[0 1 2]
 [3 4 5]]


In [25]:
np.arange(1, 26).reshape(5, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
x = np.array([10, 20, 30, 40])
x.reshape(-1, 1)
# -1 tells NumPy to automatically determine that dimension.

array([[10],
       [20],
       [30],
       [40]])

### max, min, argmax, argmin

These functions can be used to find the maximum and minimum values in an array.

argmax and argmin return the index of the maximum and minimum values, respectively.

In [27]:
a = np.array([4, 8, 2, 10, 5])

print(a.max())
print(a.min())

print(a.argmax())
print(a.argmin())


10
2
3
2


## Array Attributes

NumPy arrays have several useful attributes that provide information about the array.

### shape

shape is an attribute that tells us the size of the array along each dimension.

In [28]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.shape)

(2, 3)


### size

size tells us the total number of elements in an array.

In [29]:
a = np.arange(1, 10 ,2)
print(a.size)

5


### ndim

ndim tells us the number of dimensions of an array.

In [30]:
a = np.arange(1, 101).reshape(2, 2, 25)
print(a.ndim)

3


### dtype

Tells us the data type of the elements in an array.

In [31]:
a = np.array([1, 2, 3])
print(a.dtype)

int64


We can also specify the data type when creating the array using the dtype parameter:

In [32]:
a = np.array([1, 2, 3], dtype=float)

print(a)
print(a.dtype)

[1. 2. 3.]
float64


In [33]:
a = np.array([1, 2, 3], dtype=float)
b = np.array([1.5, 2.5, 3.5], dtype=int)
c = np.array([0, 1, 1], dtype=bool)

print(a)
print(b)
print(c)

[1. 2. 3.]
[1 2 3]
[False  True  True]


### type()

Python's built-in type() function tells us the type of the object itself, rather than the data type of the elements inside the array.

In [34]:
a = np.array([1.1, 2.2, 3.3])

print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
float64


## Indexing and Selection

NumPy indexing lets us select individual values, rows, columns, or groups of values from an array.

For machine learning data, it is useful to think of a 2D array as:

- rows → samples or observations
- columns → features

### Indexing a 1D Array

NumPy uses zero-based indexing, just like Python lists.

In [35]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


### Slicing

Slicing selects a range of values.

General syntax:

```python
array[start:stop:step]
```

\* The stop position is not included.

In [36]:
arr = np.arange(10, 21)

print(arr[2:6])
print(arr[:4])
print(arr[5:])
print(arr[::2])

[12 13 14 15]
[10 11 12 13]
[15 16 17 18 19 20]
[10 12 14 16 18 20]


### Selecting and Changing Part of an Array

We can select a slice and assign a new value to all of its elements.

In [37]:
arr = np.arange(0, 10)
arr[0:4] = 100

arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

A NumPy slice is usually a **view** of the original array, not a completely separate copy.

This is important because changing the slice can also change the original array.

In [38]:
arr = np.arange(0, 6)
part = arr[0:3]

part[:] = 99

print("part:", part)
print("arr: ", arr)

part: [99 99 99]
arr:  [99 99 99  3  4  5]


If you need an independent array, use **copy()**.

In [39]:
arr = np.arange(0, 6)
part = arr[0:3].copy()

part[:] = 99

print("part:", part)
print("arr: ", arr)

part: [99 99 99]
arr:  [0 1 2 3 4 5]


### Indexing a 2D Array

```python
array[row, column] or array[row][column]
```

Rows usually represent samples and columns represent features.

<img src= 'image\numpy_indexing.png' width=500/>

In [40]:
X = np.array([
    [20, 3, 65],
    [21, 5, 82],
    [19, 2, 58],
    [22, 7, 91]
])

print(X[0])
print(X[1, 2])
print(X[:, 0])
print(X[2, :])
print(X[:2, 1:])
print(X[[0, 2], :])

[20  3 65]
82
[20 21 19 22]
[19  2 58]
[[ 3 65]
 [ 5 82]]
[[20  3 65]
 [19  2 58]]


### Conditional Selection

A comparison creates an array of Boolean values (True and False).

We can use that Boolean array to keep only the values that satisfy a condition.

In [41]:
scores = np.array([65, 82, 58, 91, 85])

scores >= 70

array([False,  True, False,  True,  True])

In [42]:
scores[scores >= 70]

array([82, 91, 85])

We can also combine conditions.

Use:

- & for AND
- | for OR

Put each condition inside parentheses.

In [43]:
scores[(scores >= 70) & (scores < 90)]

array([82, 85])

For a 2D ML dataset, a condition can be used to select complete samples.

In [44]:
X = np.array([
    [20, 3, 65],
    [21, 5, 82],
    [19, 2, 58],
    [22, 7, 91]
])

# Select samples whose second feature is at least 5
X[X[:, 1] >= 5]

array([[21,  5, 82],
       [22,  7, 91]])

### where

np.where() can be used to find the indices of elements that satisfy a condition.

General syntax:

np.where(condition, value_if_true, value_if_false)

In [45]:
A = np.array(([[8, 1, 6],
               [3, 5, 7],
               [4, 9, 2]]))
np.where(A >= 7)

(array([0, 1, 2]), array([0, 2, 1]))

np.where() can also be used to choose between two values based on a condition:

In [46]:
x = np.array([1, 2, 3, 4, 5])
np.where(x % 2 == 0, 0, x)

array([1, 0, 3, 0, 5])

## NumPy Operations

NumPy performs numerical operations directly on arrays.

This is called vectorized computation and is one of the main reasons NumPy is useful in machine learning.

### Operations with Scalars

In [47]:
x = np.array([1, 2, 3, 4, 5])

print(x + 10)
print(x * 2)
print(x / 10)
print(x ** 2)

[11 12 13 14 15]
[ 2  4  6  8 10]
[0.1 0.2 0.3 0.4 0.5]
[ 1  4  9 16 25]


A scalar operation is applied to every element of the array. 

### Operations Between Arrays

In [48]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)

a + b: [11 22 33]
a - b: [ -9 -18 -27]
a * b: [10 40 90]
a / b: [0.1 0.1 0.1]


These operations are **element-wise**. NumPy matches elements in the same positions.

### Broadcasting

Broadcasting allows NumPy to perform operations between arrays with compatible shapes.

A common ML example is applying one value to every sample or one value to every feature.

In [49]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

X + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [50]:
feature_offsets = np.array([10, 20, 30])

X + feature_offsets

array([[11, 22, 33],
       [14, 25, 36]])

### Useful Mathematical Functions

In [51]:
x = np.array([1, 2, 4, 8])
print(x)

print("Square root:", np.sqrt(x))
print("Exponential:", np.exp(x))
print("Natural log:", np.log(x))
print("Product of all elements:", x.prod())

x = np.array([1.2, 2.7, -1.2, -2.7])
print(x)

print("Absolute value:", np.abs(x))
print("Floor:", np.floor(x))
print("Ceiling:", np.ceil(x))

[1 2 4 8]
Square root: [1.         1.41421356 2.         2.82842712]
Exponential: [2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03]
Natural log: [0.         0.69314718 1.38629436 2.07944154]
Product of all elements: 64
[ 1.2  2.7 -1.2 -2.7]
Absolute value: [1.2 2.7 1.2 2.7]
Floor: [ 1.  2. -2. -3.]
Ceiling: [ 2.  3. -1. -2.]


### Summary Statistics

In [52]:
scores = np.array([60, 70, 75, 80, 95])

print("Sum:", scores.sum())
print("Mean:", scores.mean())
print("Median:", np.median(scores))
print("Minimum:", scores.min())
print("Maximum:", scores.max())
print("Standard deviation:", scores.std())
print("Variance:", scores.var())

Sum: 380
Mean: 76.0
Median: 75.0
Minimum: 60
Maximum: 95
Standard deviation: 11.575836902790225
Variance: 134.0


### Axis Logic

For a 2D array, many operations can be performed along an axis.

- `axis=0` → calculate down the rows, producing one result for each column
- `axis=1` → calculate across the columns, producing one result for each row

For ML data, this often means:

- `axis=0` → one result for each **feature**
- `axis=1` → one result for each **sample**

<img src='image\axis_logic.png' width=400/>

In [53]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Column means:", X.mean(axis=0))
print("Row means:", X.mean(axis=1))

Column means: [4. 5. 6.]
Row means: [2. 5. 8.]


### Matrix Concatenation

NumPy provides several ways to combine arrays. The method you use depends on whether you want to join arrays along an existing dimension or create a new dimension.

#### concatenate

np.concatenate() joins arrays along an existing axis.

In [54]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

np.concatenate((A, B))
# Default axis=0: joins the arrays vertically (along the rows).

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [55]:
np.concatenate((A, B), axis=1)
# axis=1 joins the arrays horizontally (along the columns).

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### hstack and vstack

hstack Stacks arrays horizontally, joining them along the columns.

vstack Stacks arrays vertically, joining them along the rows.

\* hstack() and vstack() are convenient wrappers around concatenate() for arrays with 2 or more dimensions, but their behavior differs for 1D arrays.

In [56]:
print("hstack:\n", np.hstack((A, B)))

print("vstack:\n", np.vstack((A, B)))

f = np.arange(1,7).reshape(3,2)
d = np.arange

hstack:
 [[1 2 5 6]
 [3 4 7 8]]
vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### stack

np.stack() joins arrays along a new axis, creating a new dimension.

In [57]:
C = np.stack((A, B))

print(C)
print(C.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


### Flattening Arrays

Sometimes we need to convert a multi-dimensional array into a one-dimensional array. NumPy provides ravel() and flatten() for this purpose.

#### ravel

ravel() returns a flattened, one-dimensional version of the array.

By default, ravel() uses **row-major order (C)**.

With **column-major order (F)**, the elements are read column by column:

In [58]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.ravel())
print(A.ravel(order='F'))

[1 2 3 4 5 6]
[1 4 2 5 3 6]


#### flatten

flatten() also converts an array into a one-dimensional array.

flatten() uses row-major order (C) by default, but it also accepts the order parameter.

In [59]:
print(A.flatten())
print(A.flatten(order='F'))

[1 2 3 4 5 6]
[1 4 2 5 3 6]


#### ravel vs. flatten

- ravel **may return a view** of the original array when possible.
- flatten **always returns a copy** of the data.

### Transpose

The transpose swaps rows and columns.

We can transpose an array using .T or np.transpose()

In [60]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original shape:", X.shape)
print("Transposed shape:", X.T.shape)

X.T

Original shape: (2, 3)
Transposed shape: (3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

### inv

np.linalg.inv() calculates the **inverse of a square matrix**.

Not every matrix has an inverse. A matrix must be square and non-singular (its determinant must be non-zero) to have an inverse.

In [61]:
A = np.array([[1, 2],
              [3, 4]])
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### pinv

np.linalg.pinv() calculates the **Moore–Penrose pseudoinverse** of a matrix.

Unlike np.linalg.inv(), it can be used with **non-square matrices** and matrices that do not have a regular inverse.

In [62]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.linalg.pinv(A)

array([[-0.94444444,  0.44444444],
       [-0.11111111,  0.11111111],
       [ 0.72222222, -0.22222222]])

### Element-wise Multiplication vs Matrix Multiplication

`*` performs element-wise multiplication.

`@` performs matrix multiplication.

np.matmul() also performs matrix multiplication and is essentially the function form of the @ operator.

In [63]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Element-wise multiplication:")
print(A * B)

print("Matrix multiplication:")
print(A @ B)

Element-wise multiplication:
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]
